export {
  isWebCodecsSupported,
  isCodecSupported,
  getSupportedCodecs,
  getBitrateForConfig,
  CODEC_OPTIONS,
  RESOLUTION_OPTIONS,
  FRAMERATE_OPTIONS,
  DEFAULT_EXPORT_CONFIG,
  type VideoCodec,
  type CodecOption,
  type ResolutionOption,
  type FrameRate,
  type ExportConfig,
} from "./codec-support";
